name: Testing Actions Rules Repository
on: 
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: actions-rules-repository
        uses: lnavarrocarter/actions-rules-repository@1.1.1
        with:
          labels: |
            label1
            label2
            label3
          repo: ${{ github.repository }}
          number: 3
          github_token: ${{ secrets.GITHUB_TOKEN }}